name: flutter_b_ui_layout
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  font_awesome_flutter: ^10.4.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  go_router: ^6.2.0
  google_sign_in: ^6.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.12
  provider: ^6.0.5
  rive: ^0.10.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/rive_animations/auth/
    - assets/icons/auth/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
